variables:
  PIPELINE_CALL_TS: ""

stages: [triggers]

simple_perf:
  stage: triggers
  trigger:
    include:
    - project: 'masters-thesis-group/pipelines-repository'
      ref: master
      file: '.gitlab/ci/simple-template.yml'
    strategy: depend
    forward:
      pipeline_variables: true 
  rules:
    - if: '$PIPELINE_TYPE == "simple-perf"'

k8s_perf:
  stage: triggers
  trigger:
    include:
    - project: 'masters-thesis-group/pipelines-repository'
      ref: master
      file: '.gitlab/ci/k8s-simple-template.yml'
    strategy: depend
    forward:
      pipeline_variables: true 
  rules:
    - if: '$PIPELINE_TYPE == "k8s-perf"'